### ISSUE TITLE
Check whether optional base types can be used (e.g. `Int?`)

### ISSUE THREAD

**Issue by helje5** [Data-swift/ManagedModels#15]
Looks like CoreData itself doesn't really support them.

Another specific issue here is that `Int?` cannot be used in `@NSManaged` because `Optional<Int>` cannot be represented in ObjC (and we can't rewrite the type of a variable in a macro).

If we figure out shadowing like in Issue #14, that might be doable though.

**Comment by helje5** [comment]
This is great and would probably help with a set if issues in the list. Likely even allow for initial values! 😍

**Comment by radianttap** [comment]
I have not had time to watch Swift macros videos from WWDC, let alone try to write my own. Thus I'm doubly interested in what you do as this is great learning resource for me.

**Comment by helje5** [comment]
Fixed in 0.6.0
