### ISSUE TITLE
Circular reference resolving attached macro

### ISSUE THREAD

**Issue by radianttap** [Data-swift/ManagedModels#18]
I have a model with entities Album and Artist and many-to-many relationship between them.
Setting up inverse relationship yielded this error, not sure why it happens.

<img width="818" alt="Screenshot 2023-10-01 at 13 12 38" src="https://github.com/Data-swift/ManagedModels/assets/80697/6ff6bfab-cde6-4ca9-90ad-83ca305ddc81">

---

Possibly related: I expanded the macro to see if I can figure something out and noticed this extra space in front of `.self`, seems like a typo..?

<img width="737" alt="Screenshot 2023-10-01 at 13 13 25" src="https://github.com/Data-swift/ManagedModels/assets/80697/e80ec120-e54e-4cc8-ad7e-37b93ace7dbe">

**Comment by radianttap** [comment]
Relevant part of the model classes:

```
@Model class Artist: NSManagedObject, Decodable {
	@Relationship(inverse: \Album.artists)
	var albums: Set<Album>
}

@Model class Album: NSManagedObject, Decodable {
	@Relationship(inverse: \Artist.albums)
	var artists: Set<Artist>
}
```

**Comment by helje5** [comment]
Hm, will check. The extra space doesn't matter.

**Comment by radianttap** [comment]
Looking at SwiftData example app from WWDC 2023 (Backyard Birds), it seems only one side of the relationship should be set in code, the other side is (likely) set automatically. This is contrary to what Core Data modeller explicitly asks you to do. 🤔

Thus this does not throw compiler errors:

```
@Model class Artist: NSManagedObject, Decodable {
	var albums: Set<Album>
}

@Model class Album: NSManagedObject, Decodable {
	@Relationship(inverse: \Artist.albums)
	var artists: Set<Artist>
}
```

Still need to check if everything connects properly on context save.

**Comment by helje5** [comment]
Yes, just tried it, SwiftData has the same issue. Though I'm not entirely sure why this shouldn't be possible, maybe the compiler tries to lookup the key path during macro expansion and sees the same macro there. Good find!

At least in ManagedModels, you shouldn't don't need to specify the inverse at all, it should fine the inverse by type automagically (if it isn't ambiguous).

**Comment by helje5** [comment]
I think the CD modeller asks you to, because if the model is loaded, it doesn't add missing inverses. So it has to be configured properly up front.
Both SwiftData and ManagedModels actually discover the inverses programatically.

**Comment by radianttap** [comment]
Yep. Tested this by importing some data into the model and all the relationships were populated properly.
