### ISSUE TITLE
Strange exception thrown when assigning a value to optional to-one relationship

### ISSUE THREAD

**Issue by radianttap** [Data-swift/ManagedModels#19]
I have a `Track` and `Album` entities, where track has optional to-one `.album` relationship.

```
@Model class Track: NSManagedObject, Decodable {
	@Relationship(inverse: \Album.tracks)
	var album: Album?
}

@Model class Album: NSManagedObject, Decodable {
	var tracks: Set<Track> = []
}
```

When I try to assign a value to this `album` property, I get very strange crash that `[Album count]` is "unrecognized selector sent to instance". But don't see what could possibly be calling `count`.

Here's some screenshot of stack frames from the moment exception happens (it's different threads because this is from different attempts - each attempt gives identical frame stack):

<img width="1899" alt="Screenshot 2023-10-01 at 14 03 26" src="https://github.com/Data-swift/ManagedModels/assets/80697/d56d5fee-3a1f-4f9a-9ae8-2d32cbfce75f">
<img width="1879" alt="Screenshot 2023-10-01 at 17 49 35" src="https://github.com/Data-swift/ManagedModels/assets/80697/2d9f6dab-eb1b-4a09-8469-8d6c06ba52a1">
<img width="1154" alt="Screenshot 2023-10-01 at 17 48 51" src="https://github.com/Data-swift/ManagedModels/assets/80697/c90801ff-4e19-4d6a-b434-938f9a01b603">

Do you have any idea if this could be something in the PersistentModel implementation..?

**Comment by helje5** [comment]
I've seen the `count` thing as well. Yes, quite possible that there is a bug in my thing. Couldn't isolate it just yet.

**Comment by helje5** [comment]
I wonder whether it's related to the optional. I pushed a small change to develop that explicitly unwraps. Maybe that helps.

**Comment by helje5** [comment]
Nope, didn't fix it, investigating.

**Comment by helje5** [comment]
Even calling setValueForKey results in that, it somehow tries to coerce for some reason.
Maybe have to go back to `@NSManaged` for those.

**Comment by helje5** [comment]
Aha! They get marked as toMany.

**Comment by helje5** [comment]
To one marker (maxCount 1) not set when a property had an explicit `@Relationship`.
