### ISSUE TITLE
Xcode 15.2: "Expansion of macro '_PersistedProperty()' produced an unexpected setter"

### ISSUE THREAD

**Issue by helje5** [Data-swift/ManagedModels#25]
Meh

**Comment by helje5** [comment]
ManagedToDos doesn't compile anymore due to this.

**Comment by admkopec** [comment]
I was able to narrow down the issue to `_PersistedProperty` macro definition. While compiling with Xcode 15.2 the `@attached(accessor, names: named(init))` causes issues. Dropping the `names: named(init)` part allow the whole module to compile. As the tests are also passing after this change, I opened a PR #26.

**Comment by helje5** [comment]
Fixed in 0.8.3: https://github.com/Data-swift/ManagedModels/releases/tag/0.8.3
